#!/bin/bash
# Connect to Azure services via private endpoints
# This script configures the environment for Azure VNet integration
# Usage: ./scripts/connect-azure.sh

set -e

cd "$(dirname "$0")/.."

echo "🔷 Configuring Azure connection for Voice Journal..."
echo ""

# Check Azure CLI
if ! command -v az &> /dev/null; then
    echo "❌ Azure CLI not found. Please install it first."
    exit 1
fi

# Check login status
if ! az account show > /dev/null 2>&1; then
    echo "🔑 Not logged into Azure. Starting device code login..."
    az login --use-device-code
fi

# Get current subscription
SUBSCRIPTION=$(az account show --query name -o tsv)
echo "✅ Logged in to Azure subscription: $SUBSCRIPTION"

# Set environment variables for Azure services
echo ""
echo "📋 Setting up Azure environment variables..."

# Get secrets from Key Vault (if accessible)
KEYVAULT_NAME="kv-voicejournal-dev"

if az keyvault show --name $KEYVAULT_NAME > /dev/null 2>&1; then
    echo "   Retrieving secrets from Key Vault: $KEYVAULT_NAME"
    
    # Get PostgreSQL connection info
    POSTGRES_HOST=$(az keyvault secret show --vault-name $KEYVAULT_NAME --name postgres-host --query value -o tsv 2>/dev/null || echo "")
    POSTGRES_PASSWORD=$(az keyvault secret show --vault-name $KEYVAULT_NAME --name postgres-password --query value -o tsv 2>/dev/null || echo "")
    STORAGE_ACCOUNT=$(az keyvault secret show --vault-name $KEYVAULT_NAME --name storage-account-name --query value -o tsv 2>/dev/null || echo "")
    
    if [ -n "$POSTGRES_HOST" ]; then
        echo "   ✅ PostgreSQL host: $POSTGRES_HOST"
    fi
    if [ -n "$STORAGE_ACCOUNT" ]; then
        echo "   ✅ Storage account: $STORAGE_ACCOUNT"
    fi
else
    echo "   ⚠️  Key Vault not accessible (may need VNet integration)"
    echo "   Using environment variables from .env file"
fi

# Update .env file with Azure settings
if [ -n "$POSTGRES_HOST" ] && [ -n "$POSTGRES_PASSWORD" ]; then
    cat > api/.env << EOF
# Azure Environment Configuration (generated by connect-azure.sh)
ENVIRONMENT=azure

# Database (Azure PostgreSQL via private endpoint)
DATABASE_URL=postgresql://pgadmin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/voicejournal?sslmode=require
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_USER=pgadmin
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=voicejournal

# Storage (Azure Blob via private endpoint)
AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT:-stvoicejournaldevdata}
AZURE_STORAGE_CONTAINER_NAME=audio-files

# AI Processing (Azure OpenAI via private endpoint)
AI_PROCESSING_MODE=azure_openai
AZURE_OPENAI_ENDPOINT=https://oai-voicejournal-dev.openai.azure.com

# Authentication
JWT_SECRET_KEY=$(openssl rand -hex 32)
JWT_ALGORITHM=HS256
JWT_EXPIRATION_MINUTES=30

# CORS
ALLOWED_ORIGINS=["http://localhost:8000","http://localhost:3000"]
EOF
    echo ""
    echo "✅ Created api/.env with Azure configuration"
else
    echo ""
    echo "⚠️  Could not retrieve Azure secrets. Using local development mode."
    echo "   For VNet integration, ensure Codespaces is configured with VNet access."
fi

echo ""
echo "🚀 To start the API with Azure services:"
echo "   ./scripts/start-api.sh --azure"
